### ISSUE TITLE
npm publish Failed PUT 400;That word is not allowed

### ISSUE THREAD

**Issue by Gyumeijie** [Gyumeijie/issue-blog#2]
> 在使用npm发布package的时候遇到了一个比较少见的问题：npm publish Failed PUT 400;That word is not allowed，再给npm官方发相关邮件（support@npmjs.com）询问后，发现这个问题是由`package.json`文件中`name`字段包含了所谓的＂非法＂单词导致的。

下面是当运行`npm publish`是报的错误消息：
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@6.4.1
3 info using node@v9.0.0
4 verbose npm-session 808666e685c099ea
5 verbose publish [ '.' ]
6 info lifecycle download-from-github@1.0.0~prepublish: download-from-github@1.0.0
7 info lifecycle download-from-github@1.0.0~prepare: download-from-github@1.0.0
8 info lifecycle download-from-github@1.0.0~prepublishOnly: download-from-github@1.0.0
9 info lifecycle download-from-github@1.0.0~prepack: download-from-github@1.0.0
10 info lifecycle download-from-github@1.0.0~postpack: download-from-github@1.0.0
11 notice
12 notice 📦  download-from-github@1.0.0
13 notice === Tarball Contents ===
14 notice 757B   package.json
14 notice 168B   .eslintrc.json
14 notice 10.0kB index.js
14 notice 2.6kB  README.md
15 notice === Tarball Details ===
16 notice name:          download-from-github
16 notice version:       1.0.0
16 notice package size:  4.5 kB
16 notice unpacked size: 13.5 kB
16 notice shasum:        45db4ce6e9e0e5d6168dbec87e9707efc5573b26
16 notice integrity:     sha512-gaPv2f8iJuuOg[...]XtVH6nY5FihqQ==
16 notice total files:   4
17 notice
18 verbose getPublishConfig undefined
19 silly mapToRegistry name download-from-github
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry http://registry.npmjs.org/
22 silly mapToRegistry data { type: 'tag',
22 silly mapToRegistry   registry: true,
22 silly mapToRegistry   where: undefined,
22 silly mapToRegistry   raw: 'download-from-github',
22 silly mapToRegistry   name: 'download-from-github',
22 silly mapToRegistry   escapedName: 'download-from-github',
22 silly mapToRegistry   scope: undefined,
22 silly mapToRegistry   rawSpec: '',
22 silly mapToRegistry   saveSpec: null,
22 silly mapToRegistry   fetchSpec: 'latest',
22 silly mapToRegistry   gitRange: undefined,
22 silly mapToRegistry   gitCommittish: undefined,
22 silly mapToRegistry   hosted: undefined }
23 silly mapToRegistry uri http://registry.npmjs.org/download-from-github
24 verbose publish registryBase http://registry.npmjs.org/
25 silly publish uploading /tmp/npm-12749-e291e08d/tmp/fromDir-36617854/package.tgz
26 verbose request uri http://registry.npmjs.org/download-from-github
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 15:49:05
29 verbose request using bearer token for auth
30 verbose request id fd8ce5ad03c1f7c2
31 http request PUT http://registry.npmjs.org/download-from-github
32 http 400 http://registry.npmjs.org/download-from-github
33 verbose headers { date: 'Mon, 10 Sep 2018 07:49:05 GMT',
33 verbose headers   'content-type': 'application/json',
33 verbose headers   'content-length': '123',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'set-cookie':
33 verbose headers    [ '__cfduid=d887aa974d73ee090c2371c9e176155441536565745; expires=Tue, 10-Sep-19 07:49:05 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
33 verbose headers   'cf-ray': '45804bc456299919-LAX',
33 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
33 verbose headers   vary: 'Accept-Encoding',
33 verbose headers   server: 'cloudflare' }
34 error publish Failed PUT 400
35 verbose stack Error: That word is not allowed. Please contact support (support@npmjs.com) if you believe you received this in error. : download-from-github
35 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:329:12)
35 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:317:14)
35 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
35 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:185:22)
35 verbose stack     at emitTwo (events.js:135:13)
35 verbose stack     at Request.emit (events.js:224:7)
35 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1161:10)
35 verbose stack     at emitOne (events.js:125:13)
35 verbose stack     at Request.emit (events.js:221:7)
35 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1083:12)
35 verbose stack     at Object.onceWrapper (events.js:322:30)
35 verbose stack     at emitNone (events.js:120:20)
35 verbose stack     at IncomingMessage.emit (events.js:218:7)
35 verbose stack     at endReadableNT (_stream_readable.js:1054:12)
35 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
35 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
36 verbose statusCode 400
37 verbose pkgid download-from-github
38 verbose cwd /tmp/test/download-from-github
39 verbose Linux 4.15.0-33-generic
40 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
41 verbose node v9.0.0
42 verbose npm  v6.4.1
43 error code E400
44 error That word is not allowed. Please contact support (support@npmjs.com) if you believe you received this in error. : download-from-github
45 verbose exit [ 1, true ]
```
npm官方回的邮件内容如下：
```
Due to our spam mitigation, you are unable to publish an npm package with the word "download" in the title. I suggest selecting a different package name and trying again.
```
原来是package name 中包含了`download`这个字，重命名后运行`npm publish`就正常了。这个就比较坑了，竟然没有报是`download is not allowed` 而是 `That word is not allowed`。以后遇到这个问题的时候就要检查一下package name，估计还有其它的word不允许:joy:。

喔，对了还有[注册账号](https://www.npmjs.com/signup)的时候也是不能包含这些所谓的＂非法＂word的。

**Comment by leftstick** [comment]
nice, 那个 `The word is not allowed`简直。。。。傻到家了。害我试了好多次。。。

**Comment by czzonet** [comment]
太感谢啦！我就说acfun-download-cli这个名字提交怎么会报错

**Comment by dengnan123** [comment]
> nice, 那个 `The word is not allowed`简直。。。。傻到家了。害我试了好多次。。。

卧槽，昊哥，我刚才发包也是这个，竟然在这看到你了。。。 download 真坑
